# Generated by Django 3.1 on 2020-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_timetable',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
    ]
