# Generated by Django 3.1 on 2020-10-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_timetable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_timetable',
            name='user',
        ),
    ]
