# Generated by Django 3.0.5 on 2020-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='specialization',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
