# Generated by Django 3.0.5 on 2020-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='specialization',
            field=models.CharField(max_length=10),
        ),
    ]
