# Generated by Django 3.0.5 on 2020-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofileinfo_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rollnumber',
            field=models.PositiveIntegerField(),
        ),
    ]
