# Generated by Django 3.0.5 on 2020-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200902_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rollnumber',
            field=models.IntegerField(),
        ),
    ]
