# Generated by Django 3.0.5 on 2020-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200902_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='rollnumber',
            field=models.CharField(max_length=10),
        ),
    ]
