# Generated by Django 3.1 on 2020-09-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200902_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_tymtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=50)),
                ('First_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sec_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('third_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('fourth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('fifth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sixth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sev_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('First_lech_teacher', models.CharField(max_length=50)),
                ('sec_lech_teacher', models.CharField(max_length=50)),
                ('third_lech_teacher', models.CharField(max_length=50)),
                ('fourth_lech_teacher', models.CharField(max_length=50)),
                ('fifth_lech_teacher', models.CharField(max_length=50)),
                ('sixth_lech_teacher', models.CharField(max_length=50)),
                ('sev_lech_teacher', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
