# Generated by Django 3.1 on 2020-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_tymtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_tymtable',
            name='user',
        ),
        migrations.AddField(
            model_name='student_tymtable',
            name='specialization',
            field=models.CharField(default='', max_length=10),
        ),
    ]
