# Generated by Django 3.1 on 2020-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200914_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tymtable',
            name='First_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='fifth_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='fourth_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='sec_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='sev_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='sixth_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_tymtable',
            name='third_lech_teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
