# Generated by Django 3.1 on 2020-09-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20200914_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_tymtable',
            name='class_grp',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='class_grp',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='teacher_timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=50)),
                ('First_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sec_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('third_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('fourth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('fifth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sixth_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('sev_lech', models.CharField(blank=True, max_length=50, null=True)),
                ('First_link', models.CharField(blank=True, max_length=50, null=True)),
                ('sec_link', models.CharField(blank=True, max_length=50, null=True)),
                ('third_link', models.CharField(blank=True, max_length=50, null=True)),
                ('fourth_link', models.CharField(blank=True, max_length=50, null=True)),
                ('fifth_link', models.CharField(blank=True, max_length=50, null=True)),
                ('sixth_link', models.CharField(blank=True, max_length=50, null=True)),
                ('sev_link', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
