# Generated by Django 3.1 on 2020-09-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200915_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='class_grp',
            new_name='class_group',
        ),
    ]
