# Generated by Django 3.1 on 2020-09-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200922_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='class_group',
            new_name='class_Group',
        ),
    ]
