# Generated by Django 3.1 on 2020-09-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200922_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='First_lech',
            new_name='First_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='fifth_lech',
            new_name='fifth_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='fourth_lech',
            new_name='fourth_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='sec_lech',
            new_name='second_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='sec_link',
            new_name='second_link',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='sev_lech',
            new_name='seventh_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='sev_link',
            new_name='seventh_link',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='sixth_lech',
            new_name='sixth_lecture',
        ),
        migrations.RenameField(
            model_name='teacher_timetable',
            old_name='third_lech',
            new_name='third_lecture',
        ),
    ]
