# Generated by Django 3.1 on 2020-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_timetable',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
